# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /rscratch/zhendong/llmenv/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /rscratch/zhendong/llmenv/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /rscratch/zhendong/mfguo/warp/warp_cpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /rscratch/zhendong/mfguo/warp/warp_cpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/rscratch/zhendong/llmenv/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/rscratch/zhendong/llmenv/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /rscratch/zhendong/mfguo/warp/warp_cpp/CMakeFiles /rscratch/zhendong/mfguo/warp/warp_cpp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /rscratch/zhendong/mfguo/warp/warp_cpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example_add_float_array_cpu

# Build rule for target.
example_add_float_array_cpu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_add_float_array_cpu
.PHONY : example_add_float_array_cpu

# fast build rule for target.
example_add_float_array_cpu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cpu.dir/build.make CMakeFiles/example_add_float_array_cpu.dir/build
.PHONY : example_add_float_array_cpu/fast

#=============================================================================
# Target rules for targets named example_add_float_array_cuda

# Build rule for target.
example_add_float_array_cuda: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example_add_float_array_cuda
.PHONY : example_add_float_array_cuda

# fast build rule for target.
example_add_float_array_cuda/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cuda.dir/build.make CMakeFiles/example_add_float_array_cuda.dir/build
.PHONY : example_add_float_array_cuda/fast

example_add_float_array_cpu.o: example_add_float_array_cpu.cpp.o
.PHONY : example_add_float_array_cpu.o

# target to build an object file
example_add_float_array_cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cpu.dir/build.make CMakeFiles/example_add_float_array_cpu.dir/example_add_float_array_cpu.cpp.o
.PHONY : example_add_float_array_cpu.cpp.o

example_add_float_array_cpu.i: example_add_float_array_cpu.cpp.i
.PHONY : example_add_float_array_cpu.i

# target to preprocess a source file
example_add_float_array_cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cpu.dir/build.make CMakeFiles/example_add_float_array_cpu.dir/example_add_float_array_cpu.cpp.i
.PHONY : example_add_float_array_cpu.cpp.i

example_add_float_array_cpu.s: example_add_float_array_cpu.cpp.s
.PHONY : example_add_float_array_cpu.s

# target to generate assembly for a file
example_add_float_array_cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cpu.dir/build.make CMakeFiles/example_add_float_array_cpu.dir/example_add_float_array_cpu.cpp.s
.PHONY : example_add_float_array_cpu.cpp.s

example_add_float_array_cuda.o: example_add_float_array_cuda.cpp.o
.PHONY : example_add_float_array_cuda.o

# target to build an object file
example_add_float_array_cuda.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cuda.dir/build.make CMakeFiles/example_add_float_array_cuda.dir/example_add_float_array_cuda.cpp.o
.PHONY : example_add_float_array_cuda.cpp.o

example_add_float_array_cuda.i: example_add_float_array_cuda.cpp.i
.PHONY : example_add_float_array_cuda.i

# target to preprocess a source file
example_add_float_array_cuda.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cuda.dir/build.make CMakeFiles/example_add_float_array_cuda.dir/example_add_float_array_cuda.cpp.i
.PHONY : example_add_float_array_cuda.cpp.i

example_add_float_array_cuda.s: example_add_float_array_cuda.cpp.s
.PHONY : example_add_float_array_cuda.s

# target to generate assembly for a file
example_add_float_array_cuda.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example_add_float_array_cuda.dir/build.make CMakeFiles/example_add_float_array_cuda.dir/example_add_float_array_cuda.cpp.s
.PHONY : example_add_float_array_cuda.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... example_add_float_array_cpu"
	@echo "... example_add_float_array_cuda"
	@echo "... example_add_float_array_cpu.o"
	@echo "... example_add_float_array_cpu.i"
	@echo "... example_add_float_array_cpu.s"
	@echo "... example_add_float_array_cuda.o"
	@echo "... example_add_float_array_cuda.i"
	@echo "... example_add_float_array_cuda.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

